decoder:
  dataLoader:
    batch_size: 1000
    num_workers: 42
    shuffle: true
  lambda_kl: 0.001
  lambda_rgb: 0.01
  lambda_sdf: 1.0
  lambda_variance: 1.0
  num_batch_between_print: 1000
  num_epoch: 10
  optimizer:
    eta_decoder: 0.001
    eta_latent_space_mu: 0.02
    eta_latent_space_std: 0.01
    gammaLR: 0.9
latent_size: 6
resolution_used_for_training: 64
