decoder:
  dataLoader:
    batch_size: 10000
    num_workers: 42
    shuffle: true
  lambda_kl: 0.001
  lambda_rgb: 0.01
  lambda_sdf: 1.0
  lambda_variance: 1.0
  num_batch_between_print: 100
  num_epoch: 100
  optimizer:
    eta_decoder: 0.001
    eta_latent_space_mu: 0.02
    eta_latent_space_std: 0.01
    gamma_code_LR: 0.95
    gamma_decoder_LR: 0.98
latent_size: 6
resolution_used_for_training: 64
